[font]
normal = { family = 'JetBrainsMono Nerd Font', style = "Regular" }
size = 14.0

[keyboard]
bindings = [
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[general]
import = [ 
  "~/.config/alacritty/catppuccin-mocha.toml"
]
